# DESCRIPTION: GitLab CI/CD for libRetro (NOT FOR GitLab-proper)

##############################################################################
################################# BOILERPLATE ################################
##############################################################################

# Core definitions
.core-defs:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    JNI_PATH: libretro
    MAKEFILE_PATH: libretro
    MAKEFILE: Makefile.libretro
    CORENAME: dosbox_svn

# Core definitions
include:
  ################################## DESKTOPS ################################
  # Windows 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-x64-mingw.yml'

  # Windows 32-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-i686-mingw.yml'

  # Linux 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-x64.yml'

  # Linux 32-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-i686.yml'

  # MacOS 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/osx-x64.yml'

  ################################## CELLULAR ################################
  # Android
  - project: 'libretro-infrastructure/ci-templates'
    file: '/android-jni.yml'

  ################################## CONSOLES ################################
  # Nintendo 3DS
  - project: 'libretro-infrastructure/ci-templates'
    file: '/ctr-static.yml'
    
  # Nintendo WiiU
  - project: 'libretro-infrastructure/ci-templates'
    file: '/wiiu-static.yml'

  # Nintendo Switch
  - project: 'libretro-infrastructure/ci-templates'
    file: '/libnx-static.yml'

  # PlayStation Vita
  - project: 'libretro-infrastructure/ci-templates'
    file: '/vita-static.yml'

# Stages for building
stages:
  - build-prepare
  - build-shared
  - build-static

################################### DESKTOPS #################################
# Windows 64-bit
libretro-build-windows-x64:
  extends:
    - .libretro-windows-x64-mingw-make-default
    - .core-defs
  variables:
    CC: gcc
    CXX: g++
    platform: win
    TARGET_TRIPLET: x86_64-w64-mingw32.static
    BUNDLED_SDL: 0
  script:
    - make -C ${MAKEFILE_PATH} -f ${MAKEFILE} deps
    - make -C ${MAKEFILE_PATH} -f ${MAKEFILE} -j${NUMPROC}
    - ${TARGET_TRIPLET}-strip ${MAKEFILE_PATH}/${CORENAME}_libretro.dll

# Windows 32-bit
libretro-build-windows-i686:
  extends:
    - .libretro-windows-i686-mingw-make-default
    - .core-defs
  variables:
    CC: gcc
    CXX: g++
    platform: win
    TARGET_TRIPLET: i686-w64-mingw32.static
    BUNDLED_SDL: 0
  script:
    - make -C ${MAKEFILE_PATH} -f ${MAKEFILE} deps
    - make -C ${MAKEFILE_PATH} -f ${MAKEFILE} -j${NUMPROC}
    - ${TARGET_TRIPLET}-strip ${MAKEFILE_PATH}/${CORENAME}_libretro.dll

# Linux 64-bit
libretro-build-linux-x64:
  extends:
    - .libretro-linux-x64-make-default
    - .core-defs
  variables:
    BUNDLED_SDL: 1
  script:
    - make -C ${MAKEFILE_PATH} -f ${MAKEFILE} deps
    - make -C ${MAKEFILE_PATH} -f ${MAKEFILE} -j${NUMPROC}
    - strip ${MAKEFILE_PATH}/${CORENAME}_libretro.so

# Linux 32-bit
libretro-build-linux-i686:
  extends:
    - .libretro-linux-i686-make-default
    - .core-defs
  variables:
    BUNDLED_SDL: 1
  script:
    - make -C ${MAKEFILE_PATH} -f ${MAKEFILE} deps
    - make -C ${MAKEFILE_PATH} -f ${MAKEFILE} -j${NUMPROC}
    - strip ${MAKEFILE_PATH}/${CORENAME}_libretro.so

# MacOS 64-bit
libretro-build-osx-x64:
  extends:
    - .libretro-osx-x64-make-default
    - .core-defs
  variables:
    platform: osx
    BUNDLED_SDL: 1
    PKG_CONFIG_FLAGS: --static
  script:
    - make -C ${MAKEFILE_PATH} -f ${MAKEFILE} deps
    - export LDFLAGS="-L \"$PWD/libretro/deps_bin/lib\""
    - make -C ${MAKEFILE_PATH} -f ${MAKEFILE} -j${NUMPROC}
    - strip -u -r -S ${MAKEFILE_PATH}/${CORENAME}_libretro.dylib
    - rm -rf "${HOMEBREW_PREFIX}"

################################### CELLULAR #################################
# Android ARMv7a
android-armeabi-v7a:
  extends:
    - .libretro-android-jni-armeabi-v7a
    - .core-defs

# Android ARMv8a
android-arm64-v8a:
  extends:
    - .libretro-android-jni-arm64-v8a
    - .core-defs

# Android 64-bit x86
android-x86_64:
  extends:
    - .libretro-android-jni-x86_64
    - .core-defs

# Android 32-bit x86
android-x86:
  extends:
    - .libretro-android-jni-x86
    - .core-defs
    
################################### CONSOLES #################################
# Nintendo 3DS
libretro-build-ctr:
  extends:
    - .libretro-ctr-static-retroarch-master
    - .core-defs
  variables:
    BUNDLED_SDL: 0

# Nintendo WiiU
libretro-build-wiiu:
  extends:
    - .libretro-wiiu-static-retroarch-master
    - .core-defs
  variables:
    BUNDLED_SDL: 0

# Nintendo Switch
libretro-build-libnx-aarch64:
  extends:
    - .libretro-libnx-static-retroarch-master
    - .core-defs
  variables:
    BUNDLED_SDL: 0

# PlayStation Vita
libretro-build-vita:
  extends:
    - .libretro-vita-static-retroarch-master
    - .core-defs
  variables:
    BUNDLED_SDL: 0
